---
deployment:
  tasks:
    - export DEPLOYPATH=/home/miracelt/cardapi.itbridgenepal.com.np
    - /bin/rsync -av --delete --exclude=node_modules --exclude=.git --exclude=.env backend/ $DEPLOYPATH
    - cd $DEPLOYPATH
    - /usr/bin/npm install --production
    - /usr/bin/node seed.js
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
